[package]
name = "kms"
version = "0.2.0"
authors = [
    "Omer <omer@kzencorp.com>",
    "Gary <gary@kzencorp.com>"
]

[lib]
crate-type = ["lib"]

[dependencies]
rand = "0.6"
serde = "1.0"
serde_derive = "1.0"
paillier = { path = "/Users/tomos/cb_repos/rust-paillier"}
zk-paillier = { path = "/Users/tomos/cb_repos/zk-paillier"}
centipede = { path = "/Users/tomos/cb_repos/centipede"}
multi-party-ecdsa = { path = "/Users/tomos/cb_repos/multi-party-ecdsa" }
cfg-if = "0.1.10"

# [dependencies.paillier]
# git = "https://github.com/commerceblocks/rust-paillier"
# tag = "v0.3.7"

# [dependencies.zk-paillier]
# git = "https://github.com/commerceblocks/zk-paillier"
# tag = "v0.3.7"

# [dependencies.multi-party-schnorr]
# git = "https://github.com/commerceblock/multi-party-schnorr"
# tag = "v0.3.4"
# optional = true

[dependencies.curv]
# git = "https://github.com/commerceblock/curv"
path = "/Users/tomos/cb_repos/curv"
# tag = "v0.2.8"
features = ["ec_secp256k1"]

# [dependencies.multi-party-ecdsa]
# git = "https://github.com/commerceblock/multi-party-ecdsa"
# tag = "v0.2.7"

# [dependencies.centipede]
# git = "https://github.com/commerceblock/centipede"
# tag = "v0.2.7"

[features]
# default = ["schnorr"]
# schnorr = ["multi-party-schnorr"]
include_paillier_proofs = []
